
package net.royal.alfresco.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import net.royal.framework.web.core.UAplicacion;
import net.royal.seguridad.constante.ConstanteSeguridad;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ws_cmsService", targetNamespace = "http://ws.oefa.gob.pe/")
public class WsCmsService
    extends Service
{

    private final static URL WSCMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCMSSERVICE_EXCEPTION;
    private final static QName WSCMSSERVICE_QNAME = new QName("http://ws.oefa.gob.pe/", "ws_cmsService");
  
    static {
        URL url = null;
        WebServiceException e = null;
        try {
//        	url = new URL("http://publico.oefa.gob.pe:8080/WS_CMS/ws_cms?wsdl");
            url = new URL(UAplicacion.getServletContext().getInitParameter(ConstanteSeguridad.PREFERENCIAS_URL_ALFRESCO));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCMSSERVICE_WSDL_LOCATION = url;
        WSCMSSERVICE_EXCEPTION = e;
    }

    public WsCmsService() {
        super(__getWsdlLocation(), WSCMSSERVICE_QNAME);
    }

    public WsCmsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCMSSERVICE_QNAME, features);
    }

    public WsCmsService(URL wsdlLocation) {
        super(wsdlLocation, WSCMSSERVICE_QNAME);
    }

    public WsCmsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCMSSERVICE_QNAME, features);
    }

    public WsCmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCmsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsCms
     */
    @WebEndpoint(name = "ws_cmsPort")
    public WsCms getWsCmsPort() {
        return super.getPort(new QName("http://ws.oefa.gob.pe/", "ws_cmsPort"), WsCms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsCms
     */
    @WebEndpoint(name = "ws_cmsPort")
    public WsCms getWsCmsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.oefa.gob.pe/", "ws_cmsPort"), WsCms.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCMSSERVICE_EXCEPTION!= null) {
            throw WSCMSSERVICE_EXCEPTION;
        }
        return WSCMSSERVICE_WSDL_LOCATION;
    }

}
